"""
Global keyboard event listener via CGEventTap (Core Graphics).
Requires Accessibility permission: System Settings -> Privacy & Security -> Accessibility.

Must be run on the main thread so that TISSelectInputSource works correctly.
"""

import os
import threading

import Quartz

_OUR_PID = os.getpid()
from word_detector import WordBuffer, SEPARATORS, PUNCTUATION
from text_replacer import replace_word, replace_word_with_suffix
from layout_switcher import switch_layout_tis, keycode_to_char


class KeyListener:
    def __init__(self, word_buffer: WordBuffer):
        self.word_buffer = word_buffer
        self._tap = None
        self._replacing = threading.Event()

    def run(self) -> None:
        """Start listening. Blocks the calling thread (must be main thread)."""
        tap = Quartz.CGEventTapCreate(
            Quartz.kCGSessionEventTap,
            Quartz.kCGHeadInsertEventTap,
            Quartz.kCGEventTapOptionDefault,
            Quartz.CGEventMaskBit(Quartz.kCGEventKeyDown),
            self._callback,
            None,
        )

        if tap is None:
            print(
                'ERROR: Could not create event tap.\n'
                'Grant Accessibility permission in System Settings -> Privacy & Security -> Accessibility.'
            )
            return

        self._tap = tap
        run_loop_source = Quartz.CFMachPortCreateRunLoopSource(None, tap, 0)
        Quartz.CFRunLoopAddSource(
            Quartz.CFRunLoopGetCurrent(),
            run_loop_source,
            Quartz.kCFRunLoopCommonModes,
        )
        Quartz.CGEventTapEnable(tap, True)
        # Run loop in short intervals so Python can process signals (e.g. Ctrl+C) between ticks.
        while True:
            result = Quartz.CFRunLoopRunInMode(Quartz.kCFRunLoopDefaultMode, 0.5, False)
            if result == Quartz.kCFRunLoopRunStopped:
                break

    def stop(self) -> None:
        if self._tap:
            Quartz.CGEventTapEnable(self._tap, False)
        Quartz.CFRunLoopStop(Quartz.CFRunLoopGetMain())

    def _callback(self, proxy, event_type, event, refcon):
        if event_type != Quartz.kCGEventKeyDown:
            return event

        # Ignore events generated by our own process (backspaces, Cmd+V from replacement).
        src_pid = Quartz.CGEventGetIntegerValueField(event, Quartz.kCGEventSourceUnixProcessID)
        if src_pid == _OUR_PID:
            return event

        # Ignore Cmd+key combinations (e.g. user's own Cmd+V paste)
        flags = Quartz.CGEventGetFlags(event)
        if flags & Quartz.kCGEventFlagMaskCommand:
            return event

        keycode = Quartz.CGEventGetIntegerValueField(event, Quartz.kCGKeyboardEventKeycode)
        char = keycode_to_char(keycode) or _keycode_to_char(event)
        if char and (flags & Quartz.kCGEventFlagMaskShift):
            char = char.upper()

        if char is None:
            return event

        # Ignore all key events while replacement is in progress.
        if self._replacing.is_set():
            return event

        if char in SEPARATORS:
            word = self.word_buffer.word
            needs_fix, correct_word, lang = self.word_buffer.check_wrong_layout()
            self.word_buffer.clear()

            if word:
                if needs_fix:
                    print(f'[fix] {word!r} → {correct_word!r} ({lang})')
                else:
                    print(f'[skip] {word!r}')

            if needs_fix:
                switch_layout_tis(lang)
                if correct_word != word:
                    def _do_replace(old, new):
                        self._replacing.set()
                        try:
                            replace_word(old, new)
                        finally:
                            self._replacing.clear()
                    threading.Thread(
                        target=_do_replace,
                        args=(word, correct_word),
                        daemon=True,
                    ).start()
        elif char == '\x08' or keycode == 51:
            # Backspace — safe to call on empty buffer (no-op)
            self.word_buffer.pop()
        elif char in PUNCTUATION or char.isdigit():
            word = self.word_buffer.word
            needs_fix, correct_word, lang = self.word_buffer.check_wrong_layout()
            self.word_buffer.clear()
            if word and needs_fix:
                print(f'[fix] {word!r} → {correct_word!r} ({lang})')
                switch_layout_tis(lang)
                if correct_word != word:
                    trailing = char  # re-insert the punctuation after replacement
                    def _do_replace_punct(old, new, trail):
                        self._replacing.set()
                        try:
                            replace_word_with_suffix(old, new, trail)
                        finally:
                            self._replacing.clear()
                    threading.Thread(
                        target=_do_replace_punct,
                        args=(word, correct_word, trailing),
                        daemon=True,
                    ).start()
            elif word:
                print(f'[skip] {word!r}')
        else:
            self.word_buffer.push(char)

        return event


def _keycode_to_char(event) -> str | None:
    """Extract typed character from CGEvent."""
    try:
        char = Quartz.CGEventKeyboardGetUnicodeString(event, 1, None, None)
        if char:
            return char[1] if isinstance(char, tuple) else char
    except Exception:
        pass
    return None
